/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as QuizQuizIdRouteImport } from './routes/quiz_.$quizId'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppMistakesIndexRouteImport } from './routes/_app/mistakes/index'
import { Route as AppGoalsIndexRouteImport } from './routes/_app/goals/index'
import { Route as AppGoalsGoalIdAttemptsAttemptIdRouteImport } from './routes/_app/goals/$goalId/attempts/$attemptId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const QuizQuizIdRoute = QuizQuizIdRouteImport.update({
  id: '/quiz_/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMistakesIndexRoute = AppMistakesIndexRouteImport.update({
  id: '/mistakes/',
  path: '/mistakes/',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsIndexRoute = AppGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsGoalIdAttemptsAttemptIdRoute =
  AppGoalsGoalIdAttemptsAttemptIdRouteImport.update({
    id: '/goals/$goalId/attempts/$attemptId',
    path: '/goals/$goalId/attempts/$attemptId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof AppIndexRoute
  '/settings': typeof AppSettingsRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/goals/': typeof AppGoalsIndexRoute
  '/mistakes/': typeof AppMistakesIndexRoute
  '/goals/$goalId/attempts/$attemptId': typeof AppGoalsGoalIdAttemptsAttemptIdRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/settings': typeof AppSettingsRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/': typeof AppIndexRoute
  '/goals': typeof AppGoalsIndexRoute
  '/mistakes': typeof AppMistakesIndexRoute
  '/goals/$goalId/attempts/$attemptId': typeof AppGoalsGoalIdAttemptsAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/quiz_/$quizId': typeof QuizQuizIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/goals/': typeof AppGoalsIndexRoute
  '/_app/mistakes/': typeof AppMistakesIndexRoute
  '/_app/goals/$goalId/attempts/$attemptId': typeof AppGoalsGoalIdAttemptsAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/settings'
    | '/quiz/$quizId'
    | '/goals/'
    | '/mistakes/'
    | '/goals/$goalId/attempts/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/settings'
    | '/quiz/$quizId'
    | '/'
    | '/goals'
    | '/mistakes'
    | '/goals/$goalId/attempts/$attemptId'
  id:
    | '__root__'
    | '/$'
    | '/_app'
    | '/_app/settings'
    | '/quiz_/$quizId'
    | '/_app/'
    | '/_app/goals/'
    | '/_app/mistakes/'
    | '/_app/goals/$goalId/attempts/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  QuizQuizIdRoute: typeof QuizQuizIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/quiz_/$quizId': {
      id: '/quiz_/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof QuizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mistakes/': {
      id: '/_app/mistakes/'
      path: '/mistakes'
      fullPath: '/mistakes/'
      preLoaderRoute: typeof AppMistakesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals/': {
      id: '/_app/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof AppGoalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals/$goalId/attempts/$attemptId': {
      id: '/_app/goals/$goalId/attempts/$attemptId'
      path: '/goals/$goalId/attempts/$attemptId'
      fullPath: '/goals/$goalId/attempts/$attemptId'
      preLoaderRoute: typeof AppGoalsGoalIdAttemptsAttemptIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppGoalsIndexRoute: typeof AppGoalsIndexRoute
  AppMistakesIndexRoute: typeof AppMistakesIndexRoute
  AppGoalsGoalIdAttemptsAttemptIdRoute: typeof AppGoalsGoalIdAttemptsAttemptIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppGoalsIndexRoute: AppGoalsIndexRoute,
  AppMistakesIndexRoute: AppMistakesIndexRoute,
  AppGoalsGoalIdAttemptsAttemptIdRoute: AppGoalsGoalIdAttemptsAttemptIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  QuizQuizIdRoute: QuizQuizIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
